# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 17:34
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gabinete_saap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_gabinete', models.CharField(max_length=100)),
                ('municipio', models.CharField(max_length=250)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_saap',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('data_de_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('municipio', models.CharField(max_length=250)),
                ('uf', models.CharField(max_length=2)),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cidadao',
            fields=[
                ('usuario_saap_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autenticacao.Usuario_saap')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            bases=('autenticacao.usuario_saap',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='OrganizadorContatos',
            fields=[
                ('usuario_saap_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='autenticacao.Usuario_saap')),
                ('cartas', models.ManyToManyField(to='core.Carta')),
                ('contatos', models.ManyToManyField(to='core.Contato')),
                ('tickets', models.ManyToManyField(to='core.Ticket')),
            ],
            options={
                'abstract': False,
                'verbose_name_plural': 'users',
                'verbose_name': 'user',
            },
            bases=('autenticacao.usuario_saap',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='gabinete_saap',
            name='participantes',
            field=models.ManyToManyField(to='autenticacao.Usuario_saap'),
        ),
    ]
