# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-03 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_remetente', models.CharField(max_length=30)),
                ('municipio_remetente', models.CharField(max_length=30)),
                ('nome_destinatario', models.CharField(max_length=30)),
                ('forma_tratamento', models.CharField(max_length=30)),
                ('texto', models.CharField(max_length=1500)),
                ('data', models.DateField(auto_now=True, verbose_name='data')),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=60)),
                ('data_de_nascimento', models.DateField(verbose_name='')),
                ('sexo', models.CharField(default='', max_length=10)),
                ('telefone', models.CharField(default='', max_length=7)),
                ('celular', models.CharField(default='', max_length=8)),
                ('fax', models.CharField(default='', max_length=8)),
                ('cpf', models.CharField(default='', max_length=15)),
                ('rg', models.CharField(default='', max_length=13)),
                ('endereco', models.CharField(default='', max_length=60)),
                ('cidade', models.CharField(default='', max_length=20)),
                ('cep', models.CharField(default='', max_length=8)),
                ('estado', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(default='', max_length=30)),
                ('grupo', models.CharField(default='', max_length=20)),
                ('titulo', models.CharField(default='', max_length=30)),
                ('titulo_de_eleitor', models.CharField(default='', max_length=30)),
                ('zona', models.CharField(default='', max_length=30)),
                ('secao', models.CharField(default='', max_length=30)),
                ('profissao', models.CharField(default='', max_length=30)),
                ('cargo', models.CharField(default='', max_length=30)),
                ('empresa', models.CharField(default='', max_length=30)),
                ('dependente_nome', models.CharField(default='', max_length=30)),
                ('dependente_aniversario', models.CharField(default='', max_length=30)),
                ('dependente_parentesco', models.CharField(default='', max_length=30)),
                ('dependente_partido', models.CharField(default='', max_length=30)),
                ('dependente_data_filiacao', models.DateField(verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envio_identificado', models.BooleanField(default=False)),
                ('titulo', models.CharField(max_length=100)),
                ('corpo_texto', models.CharField(max_length=500)),
                ('remetente', models.CharField(max_length=250)),
                ('data_publicacao', models.DateField(auto_now=True, verbose_name='data_de_publicacao')),
                ('tipo_ticket', models.CharField(max_length=30)),
                ('aprovado', models.BooleanField(default=False)),
            ],
        ),
    ]
